# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtWidgets
import sys
from PyQt5.QtWidgets import QApplication, QMainWindow

from tool.readQssTool import readQssTool
from LLKGame.game import *


class Ui_Menu(QMainWindow):
    def __init__(self):
        super(Ui_Menu,self).__init__()
        self.setupUi()
        self.resize(1000,600)

    def setupUi(self):
        styleFile = "Menu.qss"
        qssStyle = readQssTool.readQss(styleFile)
        self.setStyleSheet(qssStyle)
        self.layoutWidget = QtWidgets.QWidget(self)
        self.layoutWidget.setGeometry(QtCore.QRect(325, 220, 350, 341))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda: self.openGame())
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(lambda: self.openChallengeGame())
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(lambda: self.close())
        self.verticalLayout.addWidget(self.pushButton_3)

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton.setText(_translate("Dialog", "开始游戏"))
        self.pushButton_4.setText(_translate("Dialog", "挑战模式"))
        self.pushButton_2.setText(_translate("Dialog", "排行榜"))
        self.pushButton_3.setText(_translate("Dialog", "退出游戏"))

    def getQss(self):
        styleFile = "Menu.qss"
        qssStyle = readQssTool.readQss(styleFile)
        mainWindow.setStyleSheet(qssStyle)

    def openGame(self):
        """
        Function to enter the game(normal)
        :return:
        """
        self.close()
        os.system('python ../LLKGame/game.py')

    def openChallengeGame(self):
        self.close()
        os.system('python ../LLKChallenge/challengeGame.py')


if __name__ == '__main__':
    app = QApplication(sys.argv)
    mainWindow = Ui_Menu()
    mainWindow.setWindowTitle('连连看')

    gameForm = GameForm()
    ui = Ui_game(gameForm)

    mainWindow.show()

    sys.exit(app.exec_())
